# Generated by Django 5.2.6 on 2025-09-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Отметьте, если товар должен отображаться в рекомендованных', verbose_name='Рекомендуемый товар'),
        ),
    ]
