# Generated by Django 5.2.6 on 2025-09-09 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_customer_notes_order_shipping_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('order_created', 'Создан заказ'), ('order_updated', 'Обновлен заказ'), ('order_deleted', 'Удален заказ'), ('user_created', 'Создан пользователь'), ('user_updated', 'Обновлен пользователь'), ('product_created', 'Создан товар'), ('product_updated', 'Обновлен товар'), ('product_deleted', 'Удален товар'), ('category_created', 'Создана категория'), ('category_updated', 'Обновлена категория'), ('category_deleted', 'Удалена категория'), ('login', 'Вход в систему'), ('logout', 'Выход из системы')], max_length=20, verbose_name='Тип действия')),
                ('description', models.TextField(verbose_name='Описание действия')),
                ('target_model', models.CharField(blank=True, max_length=50, verbose_name='Целевая модель')),
                ('target_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID целевого объекта')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Действие',
                'verbose_name_plural': 'Действия',
                'ordering': ['-created_at'],
            },
        ),
    ]
