# Generated by Django 5.2.6 on 2025-09-09 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
